module.exports = {
  colors: ['#fdcdd2', '#fc8a82', '#fc5457', '#fc1f3e', '#b51f23', '#fedfb4', '#fdd084', '#fc8a49', '#dd4f1d', '#b84328', '#e4dc9d', '#ffe36d', '#f4d23c', '#f6c955', '#f1b630', '#9bbc53', '#648835', '#467139', '#345c3b', '#253a25', '#a6d3c4', '#73b2af', '#5da0a9', '#368a7a', '#086352', '#66aecc', '#628baa', '#5695c0', '#1063a1', '#223774', '#7a94b1', '#8081ad', '#656b9c', '#845196', '#564b81', '#f6bbd0', '#ec989b', '#fc81ab', '#fc4482', '#f2105a', '#fffefe', '#cccccc', '#999999', '#666666', '#000000'],
  images: [{
      image: 'http://qiniu.scdztlzx.com/creator/1-2.png',
      list: ['http://qiniu.scdztlzx.com/creator/1-1.png', 'http://qiniu.scdztlzx.com/creator/1-2.png', 'http://qiniu.scdztlzx.com/creator/1-3.png', 'http://qiniu.scdztlzx.com/creator/1-4.png', 'http://qiniu.scdztlzx.com/creator/1-5.png', 'http://qiniu.scdztlzx.com/creator/1-6.png', 'http://qiniu.scdztlzx.com/creator/1-7.png', 'http://qiniu.scdztlzx.com/creator/1-8.png', 'http://qiniu.scdztlzx.com/creator/1-9.png', 'http://qiniu.scdztlzx.com/creator/1-10.png', 'http://qiniu.scdztlzx.com/creator/1-11.png', 'http://qiniu.scdztlzx.com/creator/1-12.png', 'http://qiniu.scdztlzx.com/creator/1-13.png', 'http://qiniu.scdztlzx.com/creator/1-14.png', 'http://qiniu.scdztlzx.com/creator/1-15.png', 'http://qiniu.scdztlzx.com/creator/1-16.png', 'http://qiniu.scdztlzx.com/creator/1-17.png', 'http://qiniu.scdztlzx.com/creator/1-18.png']
    },
    {
      image: 'http://qiniu.scdztlzx.com/creator/2-2.png',
      list: ['http://qiniu.scdztlzx.com/creator/2-1.png', 'http://qiniu.scdztlzx.com/creator/2-2.png', 'http://qiniu.scdztlzx.com/creator/2-3.png', 'http://qiniu.scdztlzx.com/creator/2-4.png', 'http://qiniu.scdztlzx.com/creator/2-5.png', 'http://qiniu.scdztlzx.com/creator/2-6.png', 'http://qiniu.scdztlzx.com/creator/2-7.png', 'http://qiniu.scdztlzx.com/creator/2-8.png', 'http://qiniu.scdztlzx.com/creator/2-9.png', 'http://qiniu.scdztlzx.com/creator/2-10.png', 'http://qiniu.scdztlzx.com/creator/2-11.png', 'http://qiniu.scdztlzx.com/creator/2-12.png', 'http://qiniu.scdztlzx.com/creator/2-13.png', 'http://qiniu.scdztlzx.com/creator/2-14.png', 'http://qiniu.scdztlzx.com/creator/2-15.png', 'http://qiniu.scdztlzx.com/creator/2-16.png', 'http://qiniu.scdztlzx.com/creator/2-17.png', 'http://qiniu.scdztlzx.com/creator/2-18.png']
    },
    {
      image: 'http://qiniu.scdztlzx.com/creator/3-5.png',
      list: ['http://qiniu.scdztlzx.com/creator/3-1.png', 'http://qiniu.scdztlzx.com/creator/3-2.png', 'http://qiniu.scdztlzx.com/creator/3-3.png', 'http://qiniu.scdztlzx.com/creator/3-4.png', 'http://qiniu.scdztlzx.com/creator/3-5.png', 'http://qiniu.scdztlzx.com/creator/3-6.png', 'http://qiniu.scdztlzx.com/creator/3-7.png', 'http://qiniu.scdztlzx.com/creator/3-8.png', 'http://qiniu.scdztlzx.com/creator/3-9.png', 'http://qiniu.scdztlzx.com/creator/3-10.png', 'http://qiniu.scdztlzx.com/creator/3-11.png', 'http://qiniu.scdztlzx.com/creator/3-12.png', 'http://qiniu.scdztlzx.com/creator/3-13.png', 'http://qiniu.scdztlzx.com/creator/3-14.png', 'http://qiniu.scdztlzx.com/creator/3-15.png', 'http://qiniu.scdztlzx.com/creator/3-16.png', 'http://qiniu.scdztlzx.com/creator/3-17.png', 'http://qiniu.scdztlzx.com/creator/3-18.png']
    },
    {
      image: 'http://qiniu.scdztlzx.com/creator/4-6.png',
      list: ['http://qiniu.scdztlzx.com/creator/4-1.png', 'http://qiniu.scdztlzx.com/creator/4-2.png', 'http://qiniu.scdztlzx.com/creator/4-3.png', 'http://qiniu.scdztlzx.com/creator/4-4.png', 'http://qiniu.scdztlzx.com/creator/4-5.png', 'http://qiniu.scdztlzx.com/creator/4-6.png', 'http://qiniu.scdztlzx.com/creator/4-7.png', 'http://qiniu.scdztlzx.com/creator/4-8.png', 'http://qiniu.scdztlzx.com/creator/4-9.png', 'http://qiniu.scdztlzx.com/creator/4-10.png', 'http://qiniu.scdztlzx.com/creator/4-11.png', 'http://qiniu.scdztlzx.com/creator/4-12.png', 'http://qiniu.scdztlzx.com/creator/4-13.png', 'http://qiniu.scdztlzx.com/creator/4-14.png', 'http://qiniu.scdztlzx.com/creator/4-15.png', 'http://qiniu.scdztlzx.com/creator/4-16.png', 'http://qiniu.scdztlzx.com/creator/4-17.png', 'http://qiniu.scdztlzx.com/creator/4-18.png']
    }
  ],

}